name: Build and Deploy Portfolio

on:
  push:
    branches:
      - main

env:
  AWS_REGION: 'us-east-1'
  S3_BUCKET_NAME: 'vue-blogs-frontend'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install Dependencies
      run: |
        node --version
        npm ci --production

  deploy:
    name: Deployment
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      run: echo "AWS_BUCKET_FRONT=${{ secrets.AWS_BUCKET_FRONT }}", "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}", "AWS_REGION=${{ secrets.AWS_REGION }}"

    - name: Sync Directory to S3
      run: |
        aws s3 sync deployment s3://${{ env.S3_BUCKET_NAME }}/ --delete

    - name: Invalidate CloudFront Distribution
      run: |
        aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION_FRONT }} --paths "/*"
